### ISSUE TITLE
Jenkins job is stuck

### ISSUE THREAD

**Issue by daniviga** [gem/oq-platform-standalone#35]
Two issues:

1. Jenkins job is stuck waiting for user input in apt, similar to what happened to @ptormene in IRMT
2. There's no time limit/inacivity check in the jenkins job

![Screenshot from 2019-06-17 10-06-36](https://user-images.githubusercontent.com/1818657/59588368-ba5ccd80-90e7-11e9-9342-7601c23f28b5.png)

**Comment by hascar** [comment]
I execute the zdevel build here: https://ci.openquake.org/job/zdevel_oq-platform-standalone/290/ and master build here: https://ci.openquake.org/job/master_oq-platform-standalone/1042/ and they went through without errors. I don't know if this issue can be closed.

**Comment by daniviga** [comment]
No, it can't. As discussed with @nastasi-oq I updated the base LXC images so the job is no stuck anymore, but it may happen again in the future if Ubuntu does a new libc upgrade a second time, so the issue is still relevant, at list a limit in build time must be enforced.

**Comment by daniviga** [comment]
Stale, closing
