### ISSUE TITLE
Bug: Error when loading IPT

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-platform-standalone#41]
When opening the IPT from the WebUI the following error appears:

![Uploading Screenshot 2020-12-06 at 12.48.27.png…]()

The commit https://github.com/gem/oq-platform-standalone/commit/0cc36c92baea1c6fe098deabe811c68cbbf11b28 includes a `footer.html` file not available in the repo.

@hascar

**Comment by hascar** [comment]
Hi Cata,
the screenshot seems not to work, then I wanted to ask you that since that commit is from 2019 and after others have been made, is your platform-standalone, engine and platform-ipt repo updated?

@CatalinaYepes

**Comment by CatalinaYepes** [comment]
Hi,

See the image attached.

<img width="1420" alt="WebUi_error" src="https://user-images.githubusercontent.com/6975363/101360993-ac33db80-389e-11eb-8e80-9c6a89a4b6f3.png">

I've updated all the repos for the standalone (ipt, platform, taxtweb, taxonomy) updated in master. I solve the error of opening the WebUI by removing the following lines in the file `openquakeplatform/templates/base.html` 

```
-    {% block footer %}
-    {%if gem_qgis == None %}
-    {% include "engine/includes/footer.html" %}
-    {% endif %}
-    {% endblock footer %}
```

**Comment by hascar** [comment]
Ciao @CatalinaYepes,
thanks for sharing. Actually we discovered that this problem is only with MacOs Big Sur and we are studing a method to test and fix.

Armando
